### ISSUE TITLE
Feature idea: Support salt for hash_names

### ISSUE THREAD

**Issue by dirkschumacher** [reconhub/epitrix#1]
Not adding a random salt makes the output susceptible to rainbow table attacks.
I.e. an attacker can compute hashes for popular combinations of names and other information that was used to hash the dataset and use this to break the anonymization.

I assume it would make sense to at least warn the user about that. 

A better approach would be to choose a random secret and concenate the fields with that secret as well. The resulting hash can only be reproduced by people knowing the secret (aka. the salt).

**Comment by thibautjombart** [comment]
https://github.com/reconhub/epitrix/blob/master/R/hash_names.R#L24-25

;)

Bit of a trade off between ensuring cryptography and facilitating reproducibility of hashs. But yeah that could easily be added.

**Comment by dirkschumacher** [comment]
Ahhh nice. At least there is a warning in the docs

**Comment by thibautjombart** [comment]
Added at ae24b242013d31eaf3abb0e54f778663b2ffdeea

Salt is treated by SHA1-ing the salt, then appending the resulting hash to labels, before hashing them, so one can salt with any R object basically. 

Default behaviour remains unsalted.
