### ISSUE TITLE
German umlaute are not translated in the best way

### ISSUE THREAD

**Issue by jakobschumacher** [reconhub/epitrix#12]
In the German language there are the umlaute ä ö ü and ß. There is an alternative way to write them: ae, oe, ue and ss which is not used throughout, but is still correct writing. The function "clean_labels" translates ß correctly into ss, but ä, ö, ü are translated into "a", "o" and "u". It would be better if they would translate into ae, oe and ue.

**Comment by jakobschumacher** [comment]
According to wikipedia these umlautes are quite common also in different languages. So it wont be an easy task.

**Comment by dirkschumacher** [comment]
Jakob 👋

One option is to add another parameter to `clean_labels` for the `id` of `stringi::stri_trans_general`.
Using `id = "de-ASCII"` fixes it for German Umlaute.
```R
stringi::stri_trans_general("äääß", "de-ASCII")
#> [1] "aeaeaess"
```

**Comment by jakobschumacher** [comment]
Hi, 

 

so ganz scheint das nicht zu funktionieren. Zumindest nicht bei mir:

 

> stringi::stri_trans_general("äääß", "de-ASCII")

[1] "aaass"

> sessionInfo()

R version 3.4.3 (2017-11-30)

Platform: x86_64-w64-mingw32/x64 (64-bit)

Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:

[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252

[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

 

Gruß Jakob

 

 

Von: Dirk Schumacher <notifications@github.com> 
Gesendet: Donnerstag, 11. Oktober 2018 20:28
An: reconhub/epitrix <epitrix@noreply.github.com>
Cc: Jakob Schumacher <jakob.schumacher@web.de>; Author <author@noreply.github.com>
Betreff: Re: [reconhub/epitrix] German umlaute are not translated in the best way (#12)

 

Jakob 👋

One option is to add another parameter to clean_labels for the id of stringi::stri_trans_general.
Using id = "de-ASCII" fixes it for German Umlaute.

stringi::stri_trans_general("äääß", "de-ASCII")
#> [1] "aeaeaess"

**Comment by dirkschumacher** [comment]
Not sure. Maybe it is a windows issue?

**Comment by zkamvar** [comment]
It may also be an issue with the version since they use a separate C++ library under the hood that has a different version depending on the compiler you have.
