### ISSUE TITLE
Feature: add protected symbols to clean_labels

### ISSUE THREAD

**Issue by zkamvar** [reconhub/epitrix#18]
@epiamsterdam has reported a situation where she has two labels in a variable called `death in structure < 4h` and `death in structure > 4h`. When these are passed through `clean_labels()`, they both are reduced to `death in structure 4h`. 

Thus, it would be good to have the following:

1. a `protect_symbols` argument that will take a character of symbols to keep
2. maybe a threshold argument to check if label groups above a certain percentage were lost (though, this may be some complicated coding)

**Comment by thibautjombart** [comment]
This seems to have been implemented (argument `protect`). Closing.
