### ISSUE TITLE
Example in pdf manual with formula of cv with parameter switched

### ISSUE THREAD

**Issue by BGalindo-Prieto** [reconhub/epitrix#27]
Hi,

I was reading your pdf manual and I think your parameters mu and sigma for cv calculation are switched in the example (end of page 3), even if the arg is correctly described as "cv = sigma/mu" in the args list of page 4. In page 3, the example says "cv <- mu / sigma", should not say "cv <- sigma / mu". (Apologies if I am missing something).

Link to pdf manual: https://cran.r-project.org/web/packages/epitrix/epitrix.pdf

And I just realized it is also switched here: https://www.repidemicsconsortium.org/epitrix/articles/epitrix.html

Thanks,

Beatriz

**Comment by thibautjombart** [comment]
Hi Beatriz, 

many thanks for your contribution, I think you are right, this is a typo in the example. Would you like to make a pull request to fix the typo, adding yourself as a contributor to the package in the DESCRIPTION file? Absolutely no pressure of course.

**Comment by BGalindo-Prieto** [comment]
Hi Thibaut,
Yes, sure, I will do it as soon as I can. Happy to help.
Thanks,
Beatriz

**Comment by thibautjombart** [comment]
Amazing, thanks! :)

**Comment by thibautjombart** [comment]
Thanks for flagging this. Done as of addf0a0aa758a0be6499f15262d3376a8bea13a6
