### ISSUE TITLE
Automatically renaming variable names

### ISSUE THREAD

**Issue by AmmerB** [reconhub/epitrix#3]
One issue while importing datasets can be the inconsistency in used variable name formats and criteria. One way is to advocate good data-entry practices but at the same time an automated script could help renaming variable names to some set criteria during data set import of straight after import.

Criteria: 
- All lower case
- No spaces
- No special characters

**Comment by thibautjombart** [comment]
Closed via: 99b4b06ca41ff08ed3fc51bcff4a5d70adfd0155
